# Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment
minecraft_version=1.21.1
minecraft_label=1.21.1
java_version=25
java_release=21
minecraft_version_range=[1.21.1]
neo_version=21.1.252
neo_version_range=[21.1.0,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod
mod_id=antique_atlas
mod_name=Antique Atlas
mod_description=A hand-drawn world map with biomes, structures, waypoints, and less!
mod_license=LGPL-3.0-or-later (code), CC BY-NC-SA 4.0 (textures)
mod_version=3.1.2+1.21-neoforge
mod_group_id=folk.sisby
mod_authors=Hunternif, tyra314, Sisby folk. Contributions by Kenkron, asiekierka, Haven King, TheCodeWarrior, osipxd, coolAlias, TehNut, lumiscosity, frodolon. NeoForge port by Darkona
mod_sources=https://github.com/sisby-folk/antique-atlas
archive_name=antique-atlas-neoforge

## Dependencies
ci_deps=surveyor-neoforge:surveyor_version
surveyor_version=1.2.4+1.21-neoforge
surveyor_version_range=[1.2.4,)
